workflows:
  android-workflow-id:
    name: Android CI-CD workflow
    #instance_type: windows_x2
    max_build_duration: 100
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.cicdexample"

    scripts:
      # ....
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android debug     # for building in debug mode
        script: ./gradlew assembleDebug
      - name: Build Android Release   # for building in release mode
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/**/outputs/apk/**/*.apk
  android-workflow-debug:
    name: CI-CD debug workflow
    max_build_duration: 100
    environment:
      vars:
        PACKAGE_NAME: "com.example.cicdexample"

    scripts:
      # ....
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android debug     # for building in debug mode
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/**/outputs/apk/**/*.apk
  android-workflow-release:
    name: CI-CD release workflow
    max_build_duration: 100
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.cicdexample"
    scripts:
      # ....
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Release   # for building in release mode
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/**/outputs/apk/**/*.apk
  android-workflow-firebase:
    name: CI-CD release workflow firebase
    max_build_duration: 100
    environment:
      groups:
        - firebase_token
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.cicdexample.qa"
    scripts:
      # ....
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Release   # for building in release mode
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/**/outputs/apk/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT

        android:
          app_id: 1:891973151131:android:2c30d3a3b488f49509d93e
          groups:
            - android_tester




