workflows:
  android-workflow-id:
    name: Android CI-CD workflow
    #instance_type: windows_x2
    max_build_duration: 100
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.cicdexample"

    scripts:
      # ....
      - name: C:\Users\nayana\AppData\Local\Android\Sdk
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER

    artifacts:
      - app/build/outputs/**/*.aab