workflows:
  android-workflow-id:
    name: Android CI-CD workflow
    #instance_type: windows_x2
    max_build_duration: 100
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.cicdexample"

    scripts:
      # ....
      - name: C:\Users\nayana\AppData\Local\Android\Sdk
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk